# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 4 * * 2'
  workflow_dispatch:

permissions: read-all

jobs:
  R-CMD-check:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install vignette compression tools
        if: matrix.os == 'windows-latest' || matrix.os == 'macos-latest'
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew install ghostscript qpdf
          fi
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install ghostscript qpdf
          fi
        shell: bash

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true

      - uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-4.4.1-pkg-${{ hashFiles('DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-4.4.1-pkg-

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual", "--compact-vignettes=gs+qpdf", "--as-cran")'
          error-on: 'warning'
