name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 4 * * 2'  # Every Tuesday at 4 AM UTC

permissions:
  contents: read

jobs:
  R-CMD-check:
    name: R ${{ matrix.r-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['oldrel', 'release', 'devel']
        include:
          - os: ubuntu-latest
            r-version: oldrel-1
          - os: ubuntu-latest
            r-version: oldrel-2
     #     - os: ubuntu-latest
     #       r-version: oldrel-3
     #     - os: ubuntu-latest
     #       r-version: oldrel-4
     #     - os: windows-latest
     #       r-version: oldrel-4
          - os: ubuntu-latest
            r-version: devel
            http-user-agent: release
      # Note: exclude duplicates if needed (optional)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          http-user-agent: ${{ matrix.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
