name: test-coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("devtools", "covr"))'
      - name: Run tests and upload coverage
        run: Rscript -e 'covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
